name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ github.event.number }}

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: build for testing
      run: docker build --pull --rm -f "docker/testsuite.Dockerfile" -t testsuite:PR_${{env.EVENT}} .

    - name: run unit tests
      run: docker run --rm -t testsuite:PR_${{env.EVENT}}
