name: ci

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ github.event.number }}

    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
      fail-fast: false

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install

      - name: test with pytest
        run: |
            poetry run pytest
